import type {NextPage} from "next";
import Head from "next/head";
import HomeTemplate from "../src/components/home/HomeTemplate";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Beerlot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate />
    </>
  );
};

export default Home;
