import type {NextPage} from "next";
import Head from "next/head";
import HomeTemplate from "../src/components/home/HomeTemplate";
import {useEffect, useState} from "react";
import {useRouter} from "next/router";
import Cookies from "js-cookie";
import {useUserInfoQuery} from "../hooks/query/useUserQuery";
import {filterAccessToken} from "../service/auth";
import {access} from "fs";

const Home: NextPage = () => {
  const router = useRouter();
  const isSignedUp = router.query.is_signed_up;
  const queryAccessToken = router.query.access_token;
  const cookieAccessToken = Cookies.get("beerlot-oauth-auth-request");
  const accessToken = filterAccessToken(cookieAccessToken, queryAccessToken);

  const userQuery = useUserInfoQuery(accessToken);

  useEffect(() => {
    console.log("accessToken", accessToken);
  }, [accessToken]);

  useEffect(() => {
    if (isSignedUp === "false" && typeof queryAccessToken === "string") {
      Cookies.set("beerlot-oauth-auth-guest", queryAccessToken);
      router.push("/signup");
      return;
    }

    if (isSignedUp === "true" && typeof queryAccessToken === "string") {
      Cookies.set("beerlot-oauth-auth-request", queryAccessToken);
      return;
    }
  }, [queryAccessToken, isSignedUp, router]);

  useEffect(() => {
    if (!!queryAccessToken) {
      userQuery.refetch();
      return;
    }
  }, [queryAccessToken]);

  useEffect(() => {
    if (cookieAccessToken) {
      userQuery.refetch();
      return;
    }
  }, [cookieAccessToken]);

  return (
    <>
      <Head>
        <title>Beerlot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate username={userQuery?.data?.username} />
    </>
  );
};

export default Home;
